services:

    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www/code/
            - ./.docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
            - ./.docker/nginx/cert:/etc/cert
        networks:
            - frontend
            - backend
        depends_on:
            - php
            - pgsql
        environment:
            VIRTUAL_HOST: ${APP_HOST}
            VIRTUAL_PORT: 443
            VIRTUAL_PROTO: https

    php:
        build: ./.docker/php
        volumes:
            - ./:/var/www/code/
            - ./.docker/php/config/php.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
            - backend

    pgsql:
        image: postgres:latest
        ports:
            - ${DB_PORT}:${DB_PORT}
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            PGDATA: /var/lib/postgresql/data
        networks:
            - backend

networks:
    frontend:
        external:
            name: proxy_proxy
    backend:

volumes:
    postgres-data:
